version: "3.7"

services:
  postgres:
    image: postgres:14
    container_name: admin-api-gateway-postgres
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mondbet
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
